"""``roast_target`` - optimised (targeted) transcranial electric stimulation.

Given a lead field generated by ``roast(..., recipe='leadField')`` this finds
the electrode montage that best stimulates one or more brain targets, either
maximising the intensity there or the focality around it.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
from scipy import optimize as scipy_optimize

from ..config import ORIENT_KEYWORDS, OPT_TYPES, example_dir
from ..electrodes.preproc import ElecPara, elec_preproc
from ..geometry.pointcloud import get_data_around_target
from ..io.caps import read_elec_loc
from ..io.matfile import load_mat, save_mat
from ..io.nifti import NiftiVolume
from ..preprocess.orientation import convert_to_ras_point_cloud
from ..solver.post import interpolate_to_grid
from ..targeting.optimize import (TargetingProblem, optimize, optimize_anon,
                                  optimize_prepare)
from ..utils.logging import banner, get_logger
from ..utils.matlab import cart2sph
from .log import (find_previous_run, load_options, options_path, write_target_log,
                  write_target_results)
from .options import TargetOptions
from .simulate import model_paths

__all__ = ["roast_target"]

logger = get_logger()

_ORIENT_VECTORS = {
    "right": (1.0, 0.0, 0.0), "left": (-1.0, 0.0, 0.0),
    "anterior": (0.0, 1.0, 0.0), "posterior": (0.0, -1.0, 0.0),
    "right-anterior": (1.0, 1.0, 0.0), "right-posterior": (1.0, -1.0, 0.0),
    "left-anterior": (-1.0, 1.0, 0.0), "left-posterior": (-1.0, -1.0, 0.0),
}


def _normalise_orient(orient, num_of_targets):
    """Turn the ``orient`` option into one entry per target."""
    if orient is None:
        return ["radial-in"] * num_of_targets
    if isinstance(orient, str):
        if orient.lower() not in ORIENT_KEYWORDS:
            raise ValueError("Supported orientations of electric field at the target "
                             "are: " + ", ".join(ORIENT_KEYWORDS) + ".")
        return [orient.lower()] * num_of_targets

    if isinstance(orient, (list, tuple)) and any(isinstance(o, str) for o in orient):
        if len(orient) != num_of_targets:
            raise ValueError("You want different orientations at each target. Please "
                             "provide one orientation per target.")
        out = []
        n_optimal = 0
        for one in orient:
            if isinstance(one, str):
                if one.lower() not in ORIENT_KEYWORDS:
                    raise ValueError("Supported orientations of electric field at the "
                                     "target are: " + ", ".join(ORIENT_KEYWORDS) + ".")
                if one.lower() == "optimal":
                    n_optimal += 1
                out.append(one.lower())
            else:
                vector = np.asarray(one, dtype=float).ravel()
                if vector.size != 3:
                    raise ValueError("Unrecognized customized orientation. Please enter "
                                     "the orientation vector for each target as a "
                                     "3-element vector.")
                out.append(vector)
        if n_optimal and n_optimal != num_of_targets:
            raise ValueError("roast_target() cannot perform targeting for mixed optimal "
                             "and unoptimal orientations. Please specify either "
                             "all-optimal or all-unoptimal orientations.")
        return out

    array = np.atleast_2d(np.asarray(orient, dtype=float))
    if array.shape[1] != 3:
        raise ValueError("Unrecognized customized orientation. Please enter the "
                         "orientation vector for each target as a 3-element vector.")
    if array.shape[0] == 1 and num_of_targets > 1:
        array = np.repeat(array, num_of_targets, axis=0)
    if array.shape[0] != num_of_targets:
        raise ValueError("You want different customized orientations at each target. "
                         "Please provide an N-by-3 matrix, where N is the number of "
                         "targets.")
    return [row for row in array]


def _orientation_vectors(orient, target_coord, origin):
    """Resolve the desired field orientation at every target into a unit vector."""
    u0 = np.zeros((len(orient), 3))
    for i, one in enumerate(orient):
        if isinstance(one, str):
            if one in ("radial-in", "optimal"):
                u0[i] = origin - target_coord[i]
            elif one == "radial-out":
                u0[i] = target_coord[i] - origin
            else:
                u0[i] = _ORIENT_VECTORS[one]
        else:
            u0[i] = np.asarray(one, dtype=float).ravel()
        norm = np.linalg.norm(u0[i])
        if not np.isfinite(norm) or norm == 0:
            raise ValueError(f"Orientation vector at target {i + 1} has a length close "
                             "to 0. It could be that you picked a target too close to "
                             "the brain center.")
        u0[i] = u0[i] / norm
    return u0


def _model_voxel_coords(subj, target_coord, opt_roast):
    """Bring MRI voxel coordinates into the space the model was built in."""
    coords = np.array(target_coord, dtype=float, copy=True)
    if opt_roast.is_non_ras:
        coords, perm = convert_to_ras_point_cloud(subj, coords)
    else:
        perm = np.array([0, 1, 2])
    if opt_roast.resamp:
        resolution = NiftiVolume.load(subj).resolution[perm]
        coords = np.round(coords * resolution[None, :])
    if opt_roast.zero_pad > 0:
        coords = coords + opt_roast.zero_pad
    return coords


def roast_target(subj=None, sim_tag=None, target_coord=None, *, coord_type="mni",
                 opt_type="max-l1", orient=None, desired_intensity=1.0, elec_num=None,
                 target_radius=2, k=None, targeting_tag=None, show=True):
    """Optimise an electrode montage for one or more brain targets.

    ``sim_tag`` is the tag of the ``roast`` run that generated the lead field.
    ``target_coord`` is an ``N x 3`` array in MNI (default) or voxel coordinates
    of the original MRI.
    """
    banner("ROAST is an aggregated work by Yu (Andy) Huang licensed under",
           "General Public License version 3 or later. It's supported by",
           "both NIH grants and Soterix Medical Inc.", width=61)
    banner("CHECKING INPUTS...")

    if subj is None:
        subj = example_dir() / "MNI152_T1_1mm.nii"
    if str(subj).lower() == "nyhead":
        subj = example_dir() / "nyhead.nii"
    subj = Path(subj)
    if not sim_tag:
        raise ValueError(f"Please provide a valid simulation tag for Subject {subj}, so "
                         "that roast_target() can locate the corresponding lead field.")

    option_file = options_path(subj, sim_tag, "roast")
    if not option_file.exists():
        raise FileNotFoundError(f"Option file not found. Simulation {sim_tag} may never "
                                "be run. Please run it first.")
    opt_roast = load_options(option_file, "roast")
    if opt_roast.config_txt != "leadFieldGeneration":
        raise ValueError(f"Simulation {sim_tag} was NOT run for generating the lead "
                         f"field for subject {subj}. Please run ROAST with 'leadField' "
                         "as the recipe first.")

    paths = model_paths(subj, opt_roast.subj_ras_rspd, opt_roast.t2,
                        opt_roast.multiaxial)
    if not paths.mapping.exists():
        raise FileNotFoundError(f"Mapping file {paths.mapping} not found. Please check "
                                "if you ran through STEP 1&2 in ROAST.")
    from ..io.matfile import load_spm_mapping
    image = load_spm_mapping(paths.mapping)[0]
    mri2mni = np.asarray(opt_roast.mri2mni, dtype=float)
    mni2mri = np.linalg.inv(mri2mni)

    if not paths.masks.exists():
        raise FileNotFoundError(f"Segmentation masks {paths.masks} not found.")
    mask = NiftiVolume.load(paths.masks)

    mesh_file = subj.parent / f"{subj.stem}_{sim_tag}.mat"
    if not mesh_file.exists():
        raise FileNotFoundError(f"Mesh file {mesh_file} not found.")
    mesh = load_mat(mesh_file)
    node = np.asarray(mesh["node"], dtype=float)
    elem = np.asarray(mesh["elem"], dtype=np.int64)
    face = np.asarray(mesh["face"], dtype=np.int64)

    # -- targets -----------------------------------------------------------
    if target_coord is None:
        target_coord = [[-48, -8, 50]]           # left primary motor cortex
    target_coord = np.atleast_2d(np.asarray(target_coord, dtype=float))
    if target_coord.shape[1] != 3:
        raise ValueError("Unrecognized format of target coordinates. Please enter as "
                         "[x y z].")
    if len(np.unique(target_coord, axis=0)) < len(target_coord):
        raise ValueError("Duplicated target locations. Please make sure each target is "
                         "at a different location in the brain.")
    num_of_targets = len(target_coord)

    if str(coord_type).lower() not in ("mni", "voxel"):
        raise ValueError("Please enter either 'mni' or 'voxel' for option 'coord_type'.")
    if str(opt_type).lower() not in OPT_TYPES:
        raise ValueError("Supported targeting optimizations are: " + ", ".join(OPT_TYPES))
    opt_type = str(opt_type).lower()
    orient = _normalise_orient(orient, num_of_targets)

    if "wls" in opt_type or "lcmv" in opt_type:
        if desired_intensity <= 0:
            raise ValueError("'desired_intensity' should be a positive value.")
    elif desired_intensity != 1.0:
        logger.warning("Option 'desired_intensity' will be ignored for max-intensity "
                       "optimization.")
        desired_intensity = 1.0

    if opt_type == "max-l1per":
        elec_num = 4 if elec_num is None else int(elec_num)
        if elec_num < 4 or elec_num % 2:
            raise ValueError("Please enter a positive even number of at least 4 for "
                             "option 'elec_num'.")
    elif elec_num is not None:
        logger.warning("Option 'elec_num' will be ignored for optimization type other "
                       "than 'max-l1per'.")
        elec_num = None

    if target_radius <= 0 or int(target_radius) != target_radius:
        raise ValueError("Please enter a positive integer value for option "
                         "'target_radius'.")
    target_radius = int(target_radius)

    if "wls" in opt_type:
        k = 0.2 if k is None else float(k)
        if k <= 0:
            raise ValueError("'k' should be a positive value.")
    elif k is not None:
        logger.warning("Option 'k' will be ignored for optimization type other than "
                       "weighted least square.")
        k = None

    if str(coord_type).lower() == "mni":
        target_coord_mni = target_coord.copy()
        target_coord_original = None
        voxel = np.column_stack([target_coord, np.ones(num_of_targets)])
        target_coord = np.round((mni2mri @ voxel.T).T[:, :3])
    else:
        target_coord_mni = None
        if np.any(target_coord % 1) or np.any(target_coord <= 0):
            raise ValueError("Voxel coordinates should be entered as positive integers")
        target_coord_original = target_coord.copy()
        target_coord = _model_voxel_coords(subj, target_coord, opt_roast)

    if np.any(target_coord <= 0) or np.any(target_coord > image.dim[None, :]):
        raise ValueError("Voxel coordinates should not go beyond image boundary. Please "
                         "check if you entered voxel coordinates but specified MNI "
                         "coordinates, or the other way around.")

    origin = np.round((mni2mri @ np.array([0.0, 0.0, 0.0, 1.0]))[:3])
    u0 = _orientation_vectors(orient, target_coord, origin)

    problem = TargetingProblem(
        target_coord=target_coord, num_of_targets=num_of_targets, opt_type=opt_type,
        target_radius=target_radius / image.mean_resolution, k=k,
        desired_intensity=desired_intensity, elec_num=elec_num, u=u0)

    options = TargetOptions(roast_tag=sim_tag, target_coord=target_coord,
                            target_coord_mni=target_coord_mni,
                            target_coord_original=target_coord_original,
                            opt_type=opt_type, desired_intensity=desired_intensity,
                            elec_num=elec_num, target_radius=target_radius, k=k,
                            u0=u0, orient=orient, unique_tag=targeting_tag)
    previous = find_previous_run(subj, options, "target")
    if previous is None:
        options = write_target_log(subj, options)
    else:
        if options.unique_tag and options.unique_tag != previous:
            logger.warning("The targeting with the same options has been run before "
                           "under tag '%s'. The new tag you specified '%s' will be "
                           "ignored.", previous, options.unique_tag)
        options.unique_tag = previous
    tag = options.unique_tag

    banner(f"ROAST-TARGET {subj}",
           "AT MNI COORDINATES:" if target_coord_mni is not None
           else "AT ORIGINAL MRI VOXEL COORDINATES:",
           *[str(row.astype(int).tolist())
             for row in (target_coord_mni if target_coord_mni is not None
                         else target_coord_original)],
           "...using targeting options saved in:",
           str(subj.parent / f"{subj.stem}_targetLog,"), f"under tag: {tag}")

    result_file = subj.parent / f"{subj.stem}_{tag}_targetResult.mat"
    results = None
    if not result_file.exists():
        results = _run_optimization(subj, sim_tag, tag, problem, orient, u0, node, elem,
                                    image, mask, options, result_file)
        montage = results["mon"]
    else:
        logger.info("The targeting under tag '%s' has been run before and saved in %s. "
                    "Loading the results for visualization...", tag, result_file)
        results = {key: np.asarray(value) for key, value in
                   load_mat(result_file).items() if not key.startswith("__")}
        montage = np.asarray(results["mon"], dtype=float).ravel()

    elec_name = read_elec_loc()
    ind_mon = np.flatnonzero(np.abs(montage) > 1e-3)
    logger.info("Electrodes used are:")
    for index in ind_mon:
        logger.info("%s (%.3f mA)", elec_name[index], montage[index])

    if show:
        import matplotlib.pyplot as plt
        from ..viz.results import visualize_res
        from ..viz.topoplot import topoplot

        colors = plt.get_cmap("jet")(np.linspace(0, 1, 64))
        if opt_type in ("max-l1", "max-l1per"):
            colors[2:62, :3] = 1.0          # show only the active electrodes
        figure, axis = plt.subplots(num=f"Montage in Targeting: {tag}", figsize=(6, 6))
        from matplotlib.colors import ListedColormap
        image_handle = topoplot(montage, axis=axis, cmap=ListedColormap(colors),
                                clim=(montage.min(), montage.max()))
        bar = figure.colorbar(image_handle, ax=axis)
        bar.set_label("Injected current (mA)", fontsize=14)

        _, ind_in_user_input = elec_preproc(subj, elec_name,
                                            [ElecPara(cap_type="1010")])
        visualize_res(subj, mask, mri2mni, node, elem, face, montage[ind_in_user_input],
                      image, tag, ef_mag=results["ef_mag"], ef_all=results["ef_all"],
                      xopt=results["xopt"], target_coord=results["target_coord"])

    banner("ALL DONE ROAST-TARGET")
    return {"tag": tag, "options": options, "results": results}


def _run_optimization(subj, sim_tag, tag, problem, orient, u0, node, elem, image, mask,
                      options, result_file):
    """Solve for the optimal currents and evaluate the resulting field."""
    lead_field_file = subj.parent / f"{subj.stem}_{sim_tag}_roastResult.mat"
    if not lead_field_file.exists():
        raise FileNotFoundError(
            f"Lead field not found for subject {subj} under simulation tag {sim_tag}. "
            "Please check if you ran ROAST with 'leadField' as the recipe first.")
    logger.info("Loading the lead field for targeting...")
    a_all = np.asarray(load_mat(lead_field_file)["A_all"], dtype=float)

    # Only the brain (white and gray matter) takes part in the optimisation.
    brain_nodes = np.unique(elem[(elem[:, 4] == 1) | (elem[:, 4] == 2), :4])
    A = a_all[brain_nodes - 1, :, :]

    node_voxel = np.zeros((len(node), 3))
    for i in range(3):
        node_voxel[:, i] = node[:, i] / image.mat[i, i]
    locs = node_voxel[brain_nodes - 1, :3]

    is_nan = np.isnan(A.sum(axis=(1, 2)))
    if is_nan.any():
        A = A[~is_nan]
        locs = locs[~is_nan]

    problem.n_locs = len(locs)
    n_elec = A.shape[2]
    A = A.reshape(problem.n_locs * 3, n_elec)

    problem = optimize_prepare(problem, A, locs)

    if isinstance(orient[0], str) and orient[0] == "optimal":
        t0 = np.zeros((problem.num_of_targets, 2))
        for i in range(problem.num_of_targets):
            azimuth, elevation, _ = cart2sph(u0[i, 0], u0[i, 1], u0[i, 2])
            t0[i] = [azimuth, np.pi / 2 - elevation]
        logger.info("=" * 28)
        logger.info("Searching for the optimal orientation...")
        result = scipy_optimize.minimize(
            lambda flat: optimize_anon(problem, flat.reshape(-1, 2), A),
            t0.ravel(), method="Powell", options={"disp": True})
        t_opt = result.x.reshape(-1, 2)
        u = np.zeros_like(u0)
        for i in range(problem.num_of_targets):
            u[i] = [np.cos(t_opt[i, 0]) * np.sin(t_opt[i, 1]),
                    np.sin(t_opt[i, 0]) * np.sin(t_opt[i, 1]),
                    np.cos(t_opt[i, 1])]
        problem.u = u

    i_opt = optimize(problem, A)
    montage = np.append(i_opt, -np.sum(i_opt))    # the reference Iz comes last
    logger.info("Optimization DONE!")

    # -- the field produced by the optimal montage --------------------------
    logger.info("Computing the optimized electric field (this may take a while) ...")
    is_nan_all = np.isnan(a_all.sum(axis=(1, 2)))
    valid = np.flatnonzero(~is_nan_all)
    xopt = np.zeros((valid.size, 4))
    xopt[:, 0] = valid + 1                        # 1-based node ids
    for i in range(a_all.shape[1]):
        xopt[:, i + 1] = a_all[valid][:, i, :] @ i_opt

    ef_all = np.zeros(tuple(image.dim) + (3,))
    for i in range(3):
        ef_all[..., i] = interpolate_to_grid(node_voxel[valid, :3], xopt[:, i + 1],
                                             image.dim)
    ef_mag = np.sqrt(np.sum(ef_all ** 2, axis=3))

    # -- intensity and focality at the targets ------------------------------
    mask_img = np.asarray(mask.img)
    brain = (mask_img == 1) | (mask_img == 2)
    brain_only = np.where(brain, 1.0, np.nan)
    masked_mag = ef_mag * brain_only
    finite = masked_mag[~np.isnan(masked_mag)]
    resolution = image.mean_resolution

    target_coord = problem.target_coord.astype(int)
    target_mag = np.zeros(problem.num_of_targets)
    target_int = np.zeros(problem.num_of_targets)
    target_mag_foc = np.zeros(problem.num_of_targets)
    for i, coord in enumerate(target_coord):
        index = tuple(coord - 1)
        if not np.isnan(masked_mag[index]):
            target_mag[i] = masked_mag[index]
            field = ef_all[index]
        else:
            # The target voxel is outside the brain mask: average around it.
            target_mag[i] = get_data_around_target(masked_mag, coord,
                                                   problem.target_radius)
            field = np.array([get_data_around_target(ef_all[..., c] * brain_only, coord,
                                                     problem.target_radius)
                              for c in range(3)])
        # Focality: the cube root of the volume above half the target intensity.
        target_mag_foc[i] = (np.sum(finite >= target_mag[i] * 0.5) ** (1 / 3)
                             * resolution / 10)          # in cm
        target_int[i] = float(np.dot(field, problem.u[i]))

    elec_name = read_elec_loc()
    ind_mon = np.flatnonzero(np.abs(montage) > 1e-3)
    montage_txt = ", ".join(f"{elec_name[i]} ({montage[i]:.3f} mA)" for i in ind_mon)

    results = {"mon": montage, "xopt": xopt, "ef_all": ef_all, "ef_mag": ef_mag,
               "target_mag": target_mag, "target_int": target_int,
               "target_mag_foc": target_mag_foc, "target_coord": target_coord,
               "montage_txt": montage_txt}
    write_target_results(subj, {"montage_txt": montage_txt, "target_mag": target_mag,
                                "target_int": target_int,
                                "target_mag_foc": target_mag_foc})
    save_mat(result_file, {k: v for k, v in results.items() if k != "montage_txt"}
             | {"montage_txt": montage_txt})
    return results
